### ISSUE TITLE
error in lines 317, 310

### ISSUE THREAD

**Issue by osnattirosh** [yuhanH/HPViewer#1]
this is the error I got when trying to run HPViewer on a sample metagenomic data - 
Traceback (most recent call last):
  File "/home/tirosho/HPViewer/HPViewer.py", line 317, in <module>
    quant_HPV(outprefix,min_cov)        
  File "/home/tirosho/HPViewer/HPViewer.py", line 310, in quant_HPV
    coverage=str("%.4f" % (1000*float(d2[hpv])/float(d3[hpv])))
KeyError: 'HPV131'

I checked and saw HPV131 is not in the distant matrix database. does this cause the problem? or something else?

updating - I just tried it with another file and got the same error for HPV150, I guess it's not the HPV type that is the problem. Am I missing a python module?

**Comment by yuhanH** [comment]
If the HPV is not in the matrix, it means that this HPV doesn't share any homologous fragments with other types of HPV.
