### ISSUE TITLE
cov option does not work

### ISSUE THREAD

**Issue by RoelKluin** [yuhanH/HPViewer#2]
-cov option does not work, will be interpreted as -o v
resulting in a 'v' directory wherein all your output is continuously overwritten.

fix hint: replace cov by single character option c:

```
print("   -c    <INT>    minimal coverage threshold to determine HPV present, default is 150 bp.")
...
getopt.getopt( sys.argv[1:], "U:1:2:m:o:p:c:h", ["help" ] )
...
if opt in ( "-c", ):
            min_cov = str(val)

```

**Comment by yuhanH** [comment]
Hi,
Sorry for the late reply! Thanks to report this error. I have fixed it changing "-cov" to "-c", just like your suggestion.
